apiVersion: apps/v1
kind: Deployment
metadata:
  name: avaliacao-rabbitmq
spec:
  selector:
    matchLabels:
      app: avaliacao-rabbitmq
  template:
    metadata:
      labels:
        app: avaliacao-rabbitmq
    spec:
      containers:
        - name: rabbitmq
          image: rabbitmq:3-management
          ports:
            - containerPort: 5672
            - containerPort: 15672
---
apiVersion: v1
kind: Service
metadata:
  name: avaliacao-rabbitmq
spec:
  ports:
    - port: 5672
    - port: 15672
  selector:
    app: avaliacao-rabbitmq