apiVersion: apps/v1
kind: Deployment
metadata:
  name: avaliacao-service
  labels:
    app: avaliacao-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: avaliacao-service
  template:
    metadata:
      labels:
        app: avaliacao-service
    spec:
      containers:
        - name: avaliacao-service
          image: carwilfer/avaliacao-service:latest
          ports:
            - containerPort: 8090
          env:
            - name: postgres
              value: jdbc:postgresql://postgres:5432/postgres
            - name: rabbithost
              value: rabbitmq
            - name: ZIPKINENDPOINT
              value: http://zipkin:9411/api/v2/spans

---

apiVersion: v1
kind: Service
metadata:
  name: avaliacao-service
spec:
  type: ClusterIP
  ports:
    - port: 8090
      targetPort: 8090
      protocol: TCP
  selector:
    app: avaliacao-service