apiVersion: apps/v1
kind: Deployment
metadata:
  name: compra-service
  labels:
    app: compra-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: compra-service
  template:
    metadata:
      labels:
        app: compra-service
    spec:
      containers:
        - name: compra-service
          image: carwilfer/compra-service:latest
          ports:
            - containerPort: 8088
          env:
            - name: postgres
              value: jdbc:postgresql://postgres:5432/postgres
            - name: rabbithost
              value: rabbitmq
            - name: ZIPKINENDPOINT
              value: http://zipkin:9411/api/v2/spans

---

apiVersion: v1
kind: Service
metadata:
  name: compra-service
spec:
  type: ClusterIP
  ports:
    - port: 8088
      targetPort: 8088
      protocol: TCP
  selector:
    app: compra-service