apiVersion: apps/v1
kind: Deployment
metadata:
  name: compra-service
  labels:
    app: compra
spec:
  replicas: 2
  selector:
    matchLabels:
      app: compra
  template:
    metadata:
      labels:
        app: compra
    spec:
      containers:
        - name: compra-service
          image: carwilfer/compra-service:latest
          ports:
            - containerPort: 8088
          env:
            - name: SPRING_DATASOURCE_URL
              value: jdbc:postgresql://compra-postgres:5432/compra_db
            - name: SPRING_DATASOURCE_USERNAME
              value: postgres
            - name: SPRING_DATASOURCE_PASSWORD
              value: postgres
            - name: SPRING_RABBITMQ_HOST
              value: compra-rabbitmq

---

apiVersion: v1
kind: Service
metadata:
  name: compra-service
spec:
  selector:
    app: compra
  ports:
    - protocol: TCP
      port: 8088
      targetPort: 8088
      nodePort: 30501
  type: LoadBalancer