apiVersion: apps/v1
kind: Deployment
metadata:
  name: empresa-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: empresa-service
  template:
    metadata:
      labels:
        app: empresa-service
    spec:
      containers:
        - name: empresa-service
          image: carwilfer/empresa-service:latest
          ports:
            - containerPort: 8085
          env:
            - name: postgres
              value: jdbc:postgresql://postgres:5432/postgres
            - name: rabbithost
              value: rabbitmq
            - name: ZIPKINENDPOINT
              value: http://zipkin:9411/api/v2/spans

---
apiVersion: v1
kind: Service
metadata:
  name: empresa-service
spec:
  type: ClusterIP
  ports:
    - port: 8085
      targetPort: 8085
      protocol: TCP
  selector:
    app: empresa-service