apiVersion: apps/v1
kind: Deployment
metadata:
  name: jogador-service
  labels:
    app: jogador-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: jogador-service
  template:
    metadata:
      labels:
        app: jogador-service
    spec:
      containers:
        - name: jogador-service
          image: carwilfer/jogador-service:latest
          ports:
            - containerPort: 8086
          env:
            - name: postgres
              value: jdbc:postgresql://postgres:5432/postgres
            - name: rabbithost
              value: rabbitmq
            - name: ZIPKINENDPOINT
              value: http://zipkin:9411/api/v2/spans

---

---
apiVersion: v1
kind: Service
metadata:
  name: jogador-service
spec:
  type: ClusterIP
  ports:
    - port: 8086
      targetPort: 8086
      protocol: TCP
  selector:
    app: jogador-service