apiVersion: apps/v1
kind: Deployment
metadata:
  name: jogador-service
  labels:
    app: jogador
spec:
  replicas: 2
  selector:
    matchLabels:
      app: jogador
  template:
    metadata:
      labels:
        app: jogador
    spec:
      containers:
        - name: jogador
          image: carwilfer/jogador-service:latest
          ports:
            - containerPort: 8086
          env:
            - name: SPRING_DATASOURCE_URL
              value: jdbc:postgresql://jogador-postgres:5432/jogador_db
            - name: SPRING_DATASOURCE_USERNAME
              value: postgres
            - name: SPRING_DATASOURCE_PASSWORD
              value: postgres
            - name: SPRING_RABBITMQ_HOST
              value: jogador-rabbitmq

---

apiVersion: v1
kind: Service
metadata:
  name: jogador-service
spec:
  type: LoadBalancer
  ports:
    - port: 8086
      targetPort: 8086
      nodePort: 30504
  selector:
    app: jogador