apiVersion: apps/v1
kind: Deployment
metadata:
  name: jogo-service
  labels:
    app: jogo-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: jogo-service
  template:
    metadata:
      labels:
        app: jogo-service
    spec:
      containers:
        - name: jogo-service
          image: carwilfer/jogo-service:latest
          ports:
            - containerPort: 8087
          env:
            - name: postgres
              value: jdbc:postgresql://postgres:5432/postgres
            - name: rabbithost
              value: rabbitmq
            - name: ZIPKINENDPOINT
              value: http://zipkin:9411/api/v2/spans

---
apiVersion: v1
kind: Service
metadata:
  name: jogo-service
spec:
  type: ClusterIP
  ports:
    - port: 8087
      targetPort: 8087
      protocol: TCP
  selector:
    app: jogo-service