apiVersion: apps/v1
kind: Deployment
metadata:
  name: usuario-postgres
spec:
  selector:
    matchLabels:
      app: usuario-postgres
  template:
    metadata:
      labels:
        app: usuario-postgres
    spec:
      containers:
        - name: postgres
          image: postgres:14
          env:
            - name: POSTGRES_DB
              value: usuario_db
            - name: POSTGRES_USER
              value: postgres
            - name: POSTGRES_PASSWORD
              value: postgres
          ports:
            - containerPort: 5432
---
apiVersion: v1
kind: Service
metadata:
  name: usuario-postgres
spec:
  ports:
    - port: 5432
  selector:
    app: usuario-postgres