apiVersion: apps/v1
kind: Deployment
metadata:
  name: conta-service
  labels:
    app: conta
spec:
  replicas: 2
  selector:
    matchLabels:
      app: conta
  template:
    metadata:
      labels:
        app: conta
    spec:
      containers:
        - name: conta-service
          image: conta-service:latest
          ports:
            - containerPort: 8089
          env:
            - name: SPRING_DATASOURCE_URL
              value: jdbc:postgresql://conta-postgres:5432/conta_db
            - name: SPRING_DATASOURCE_USERNAME
              value: postgres
            - name: SPRING_DATASOURCE_PASSWORD
              value: postgres
            - name: SPRING_RABBITMQ_HOST
              value: conta-rabbitmq

---

apiVersion: v1
kind: Service
metadata:
  name: conta-service
spec:
  selector:
    app: conta
  ports:
    - protocol: TCP
      port: 8089
      targetPort: 8089
  type: LoadBalancer