apiVersion: apps/v1
kind: Deployment
metadata:
  name: jogador-rabbitmq
spec:
  selector:
    matchLabels:
      app: jogador-rabbitmq
  template:
    metadata:
      labels:
        app: jogador-rabbitmq
    spec:
      containers:
        - name: rabbitmq
          image: rabbitmq:3-management
          ports:
            - containerPort: 5672
            - containerPort: 15672
---
apiVersion: v1
kind: Service
metadata:
  name: jogador-rabbitmq
spec:
  selector:
    app: jogador-rabbitmq
  ports:
    - name: amqp
      port: 5672
      targetPort: 5672
    - name: management
      port: 15672
      targetPort: 15672
  type: ClusterIP