name: CI-CD

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven

      - name: Build and package avaliacao
        working-directory: ./avaliacao
        run: mvn clean package

      - name: Build and package compra
        working-directory: ./compra
        run: mvn clean package

      - name: Build and package conta
        working-directory: ./conta
        run: mvn clean package

      - name: Build and package empresa
        working-directory: ./empresa
        run: mvn clean package

      - name: Build and package jogador
        working-directory: ./jogador
        run: mvn clean package

      - name: Build and package jogo
        working-directory: ./jogo
        run: mvn clean package

      - name: Build and package usuario
        working-directory: ./usuario
        run: mvn clean package

      - name: Upload JAR artifacts
        uses: actions/upload-artifact@v3
        with:
          name: all-microservices
          path: |
            avaliacao/target/*.jar
            compra/target/*.jar
            conta/target/*.jar
            empresa/target/*.jar
            jogador/target/*.jar
            jogo/target/*.jar
            usuario/target/*.jar

  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Download JAR artifacts
        uses: actions/download-artifact@v3
        with:
          name: all-microservices

      - name: Deploy to server
        run: |
          # Comandos para fazer o deploy dos JARs para o servidor
          # Isso pode envolver copiar os JARs para o servidor e reiniciar as aplicações
          scp avaliacao/target/*.jar compra/target/*.jar conta/target/*.jar empresa/target/*.jar jogador/target/*.jar jogo/target/*.jar usuario/target/*.jar user@server:/path/to/deploy/
          ssh user@server 'sudo systemctl restart myapp'